"""Unit tests for Phase 2 (Merton structural PD baseline).

Core check: the fsolve-based solver recovers known (V, sigma_V) from
synthetic (E, sigma_E) generated by running the *forward* Merton equations
-- the "solver converges on a synthetic test case with a known answer"
check the plan calls for in Phase 10, worth having from the start.
"""

import numpy as np
import pandas as pd
import pytest
from scipy.stats import norm

from src.pd_model import (
    compute_merton_panel,
    distance_to_default,
    merton_pd,
    solve_merton,
)


def _merton_forward(V: float, sigma_V: float, D: float, r: float, T: float) -> tuple[float, float]:
    """Forward Merton equations: given true (V, sigma_V), compute the
    (E, sigma_E) an equity investor would observe. Inverse of solve_merton.
    """
    sqrt_T = np.sqrt(T)
    d1 = (np.log(V / D) + (r + 0.5 * sigma_V ** 2) * T) / (sigma_V * sqrt_T)
    d2 = d1 - sigma_V * sqrt_T
    E = V * norm.cdf(d1) - D * np.exp(-r * T) * norm.cdf(d2)
    sigma_E = norm.cdf(d1) * sigma_V * V / E
    return E, sigma_E


@pytest.mark.parametrize("V_true,sigma_V_true,D,r,T", [
    (150.0, 0.25, 100.0, 0.04, 1.0),   # moderate leverage, investment-grade-like
    (120.0, 0.45, 100.0, 0.04, 1.0),   # higher leverage, riskier
    (500.0, 0.15, 50.0, 0.03, 1.0),    # low leverage, very safe
])
def test_solve_merton_recovers_known_asset_value_and_vol(V_true, sigma_V_true, D, r, T):
    E, sigma_E = _merton_forward(V_true, sigma_V_true, D, r, T)

    V_hat, sigma_V_hat, converged, residual_norm = solve_merton(E, sigma_E, D, r, T)

    assert converged
    assert residual_norm < 1e-6
    assert V_hat == pytest.approx(V_true, rel=1e-4)
    assert sigma_V_hat == pytest.approx(sigma_V_true, rel=1e-4)


def test_solve_merton_rejects_nonpositive_debt():
    with pytest.raises(ValueError):
        solve_merton(E=100.0, sigma_E=0.3, D=0.0, r=0.04, T=1.0)


def test_distance_to_default_and_pd_are_consistent():
    # Deep in the money (V >> D): DD should be large and PD near zero.
    dd_safe = distance_to_default(V=1000.0, sigma_V=0.2, D=100.0, r=0.04, T=1.0)
    assert dd_safe > 3
    assert merton_pd(dd_safe) < 0.01

    # Near the default boundary (V close to D): DD should be small/negative,
    # PD meaningfully elevated.
    dd_risky = distance_to_default(V=105.0, sigma_V=0.5, D=100.0, r=0.04, T=1.0)
    assert dd_risky < dd_safe
    assert merton_pd(dd_risky) > merton_pd(dd_safe)


def test_merton_pd_rank_orders_credit_quality():
    # Higher-leverage / higher-vol name should get a strictly higher PD than
    # a lower-leverage / lower-vol name, all else equal.
    dd_investment_grade = distance_to_default(V=200.0, sigma_V=0.2, D=100.0, r=0.04, T=1.0)
    dd_stressed = distance_to_default(V=110.0, sigma_V=0.6, D=100.0, r=0.04, T=1.0)

    assert merton_pd(dd_stressed) > merton_pd(dd_investment_grade)


def test_compute_merton_panel_skips_missing_or_nonpositive_debt():
    panel = pd.DataFrame([
        {"ticker": "GOOD", "equity_value": 1000.0, "equity_vol": 0.3, "total_debt_face_value": 200.0},
        {"ticker": "NODEBT", "equity_value": 500.0, "equity_vol": 0.2, "total_debt_face_value": 0.0},
        {"ticker": "MISSING", "equity_value": None, "equity_vol": 0.2, "total_debt_face_value": 100.0},
    ])
    result = compute_merton_panel(panel, r=0.04, T=1.0)

    good = result.set_index("ticker").loc["GOOD"]
    assert good["converged"]
    assert good["pd_merton"] is not None

    for ticker in ("NODEBT", "MISSING"):
        row = result.set_index("ticker").loc[ticker]
        assert row["converged"] == False  # noqa: E712 (may be a numpy bool)
        assert row["skip_reason"] == "missing_or_nonpositive_input"
        assert pd.isna(row["pd_merton"])
